# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_maket_error_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 302)
        self.label_img = QtWidgets.QLabel(Dialog)
        self.label_img.setGeometry(QtCore.QRect(20, 20, 241, 261))
        self.label_img.setObjectName("label_img")
        self.label_err = QtWidgets.QLabel(Dialog)
        self.label_err.setGeometry(QtCore.QRect(310, 60, 211, 31))
        self.label_err.setObjectName("label_err")
        self.label_text_err = QtWidgets.QLabel(Dialog)
        self.label_text_err.setGeometry(QtCore.QRect(300, 120, 291, 101))
        self.label_text_err.setObjectName("label_text_err")
        self.button_Ok = QtWidgets.QPushButton(Dialog)
        self.button_Ok.setGeometry(QtCore.QRect(500, 250, 93, 28))
        self.button_Ok.setObjectName("button_Ok")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ошибка"))
        self.label_img.setText(_translate("Dialog", "img"))
        self.label_err.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-style:italic;\">Ой! Ошибка..</span></p></body></html>"))
        self.label_text_err.setText(_translate("Dialog", "текст ошибки"))
        self.button_Ok.setText(_translate("Dialog", "Закрыть"))
