# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_maket_help_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(628, 336)
        self.button_Ok = QtWidgets.QPushButton(Dialog)
        self.button_Ok.setGeometry(QtCore.QRect(510, 290, 93, 28))
        self.button_Ok.setObjectName("button_Ok")
        self.label_img = QtWidgets.QLabel(Dialog)
        self.label_img.setGeometry(QtCore.QRect(30, 20, 201, 301))
        self.label_img.setObjectName("label_img")
        self.textEdit_helpText = QtWidgets.QTextEdit(Dialog)
        self.textEdit_helpText.setGeometry(QtCore.QRect(270, 20, 331, 251))
        self.textEdit_helpText.setObjectName("textEdit_helpText")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Справка"))
        self.button_Ok.setText(_translate("Dialog", "Закрыть"))
        self.label_img.setText(_translate("Dialog", "img"))
